namespace Refs
{
    public static class Libs
    {


        public static IEnumerable<ILib> GetAssembliesWithNamespace(string @namespace)
        {
            return Items.Where(c => c.Namespaces.Contains(@namespace));
        }

        public static ILib? ResolveLibraryByFilename(string filename)
        {
            return Items.Where(c => filename.EndsWith(Path.DirectorySeparatorChar + c.File)).FirstOrDefault();
        }

        /// <summary>
        /// REturn the list of assemblies
        /// </summary>
        public static IEnumerable<ILib> Items
        {
            get
            {
                yield return Accessibility.Default;
                yield return DirectWriteForwarder.Default;
                yield return Microsoft.AspNetCore.Default;
                yield return Microsoft.AspNetCore.Antiforgery.Default;
                yield return Microsoft.AspNetCore.Authentication.Default;
                yield return Microsoft.AspNetCore.Authentication.Abstractions.Default;
                yield return Microsoft.AspNetCore.Authentication.BearerToken.Default;
                yield return Microsoft.AspNetCore.Authentication.Cookies.Default;
                yield return Microsoft.AspNetCore.Authentication.Core.Default;
                yield return Microsoft.AspNetCore.Authentication.OAuth.Default;
                yield return Microsoft.AspNetCore.Authorization.Default;
                yield return Microsoft.AspNetCore.Authorization.Policy.Default;
                yield return Microsoft.AspNetCore.Components.Default;
                yield return Microsoft.AspNetCore.Components.Authorization.Default;
                yield return Microsoft.AspNetCore.Components.Endpoints.Default;
                yield return Microsoft.AspNetCore.Components.Forms.Default;
                yield return Microsoft.AspNetCore.Components.Server.Default;
                yield return Microsoft.AspNetCore.Components.Web.Default;
                yield return Microsoft.AspNetCore.Connections.Abstractions.Default;
                yield return Microsoft.AspNetCore.CookiePolicy.Default;
                yield return Microsoft.AspNetCore.Cors.Default;
                yield return Microsoft.AspNetCore.Cryptography.Internal.Default;
                yield return Microsoft.AspNetCore.Cryptography.KeyDerivation.Default;
                yield return Microsoft.AspNetCore.DataProtection.Default;
                yield return Microsoft.AspNetCore.DataProtection.Abstractions.Default;
                yield return Microsoft.AspNetCore.DataProtection.Extensions.Default;
                yield return Microsoft.AspNetCore.Diagnostics.Default;
                yield return Microsoft.AspNetCore.Diagnostics.Abstractions.Default;
                yield return Microsoft.AspNetCore.Diagnostics.HealthChecks.Default;
                yield return Microsoft.AspNetCore.HostFiltering.Default;
                yield return Microsoft.AspNetCore.Hosting.Default;
                yield return Microsoft.AspNetCore.Hosting.Abstractions.Default;
                yield return Microsoft.AspNetCore.Hosting.Server.Abstractions.Default;
                yield return Microsoft.AspNetCore.Html.Abstractions.Default;
                yield return Microsoft.AspNetCore.Http.Default;
                yield return Microsoft.AspNetCore.Http.Abstractions.Default;
                yield return Microsoft.AspNetCore.Http.Connections.Default;
                yield return Microsoft.AspNetCore.Http.Connections.Common.Default;
                yield return Microsoft.AspNetCore.Http.Extensions.Default;
                yield return Microsoft.AspNetCore.Http.Features.Default;
                yield return Microsoft.AspNetCore.Http.Results.Default;
                yield return Microsoft.AspNetCore.HttpLogging.Default;
                yield return Microsoft.AspNetCore.HttpOverrides.Default;
                yield return Microsoft.AspNetCore.HttpsPolicy.Default;
                yield return Microsoft.AspNetCore.Identity.Default;
                yield return Microsoft.AspNetCore.Localization.Default;
                yield return Microsoft.AspNetCore.Localization.Routing.Default;
                yield return Microsoft.AspNetCore.Metadata.Default;
                yield return Microsoft.AspNetCore.Mvc.Default;
                yield return Microsoft.AspNetCore.Mvc.Abstractions.Default;
                yield return Microsoft.AspNetCore.Mvc.ApiExplorer.Default;
                yield return Microsoft.AspNetCore.Mvc.Core.Default;
                yield return Microsoft.AspNetCore.Mvc.Cors.Default;
                yield return Microsoft.AspNetCore.Mvc.DataAnnotations.Default;
                yield return Microsoft.AspNetCore.Mvc.Formatters.Json.Default;
                yield return Microsoft.AspNetCore.Mvc.Formatters.Xml.Default;
                yield return Microsoft.AspNetCore.Mvc.Localization.Default;
                yield return Microsoft.AspNetCore.Mvc.Razor.Default;
                yield return Microsoft.AspNetCore.Mvc.RazorPages.Default;
                yield return Microsoft.AspNetCore.Mvc.TagHelpers.Default;
                yield return Microsoft.AspNetCore.Mvc.ViewFeatures.Default;
                yield return Microsoft.AspNetCore.OutputCaching.Default;
                yield return Microsoft.AspNetCore.RateLimiting.Default;
                yield return Microsoft.AspNetCore.Razor.Default;
                yield return Microsoft.AspNetCore.Razor.Runtime.Default;
                yield return Microsoft.AspNetCore.RequestDecompression.Default;
                yield return Microsoft.AspNetCore.ResponseCaching.Default;
                yield return Microsoft.AspNetCore.ResponseCaching.Abstractions.Default;
                yield return Microsoft.AspNetCore.ResponseCompression.Default;
                yield return Microsoft.AspNetCore.Rewrite.Default;
                yield return Microsoft.AspNetCore.Routing.Default;
                yield return Microsoft.AspNetCore.Routing.Abstractions.Default;
                yield return Microsoft.AspNetCore.Server.HttpSys.Default;
                yield return Microsoft.AspNetCore.Server.IIS.Default;
                yield return Microsoft.AspNetCore.Server.IISIntegration.Default;
                yield return Microsoft.AspNetCore.Server.Kestrel.Default;
                yield return Microsoft.AspNetCore.Server.Kestrel.Core.Default;
                yield return Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes.Default;
                yield return Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Default;
                yield return Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Default;
                yield return Microsoft.AspNetCore.Session.Default;
                yield return Microsoft.AspNetCore.SignalR.Default;
                yield return Microsoft.AspNetCore.SignalR.Common.Default;
                yield return Microsoft.AspNetCore.SignalR.Core.Default;
                yield return Microsoft.AspNetCore.SignalR.Protocols.Json.Default;
                yield return Microsoft.AspNetCore.StaticFiles.Default;
                yield return Microsoft.AspNetCore.WebSockets.Default;
                yield return Microsoft.AspNetCore.WebUtilities.Default;
                yield return Microsoft.CSharp.Default;
                yield return Microsoft.Extensions.Caching.Abstractions.Default;
                yield return Microsoft.Extensions.Caching.Memory.Default;
                yield return Microsoft.Extensions.Configuration.Default;
                yield return Microsoft.Extensions.Configuration.Abstractions.Default;
                yield return Microsoft.Extensions.Configuration.Binder.Default;
                yield return Microsoft.Extensions.Configuration.CommandLine.Default;
                yield return Microsoft.Extensions.Configuration.EnvironmentVariables.Default;
                yield return Microsoft.Extensions.Configuration.FileExtensions.Default;
                yield return Microsoft.Extensions.Configuration.Ini.Default;
                yield return Microsoft.Extensions.Configuration.Json.Default;
                yield return Microsoft.Extensions.Configuration.KeyPerFile.Default;
                yield return Microsoft.Extensions.Configuration.UserSecrets.Default;
                yield return Microsoft.Extensions.Configuration.Xml.Default;
                yield return Microsoft.Extensions.DependencyInjection.Default;
                yield return Microsoft.Extensions.DependencyInjection.Abstractions.Default;
                yield return Microsoft.Extensions.Diagnostics.Default;
                yield return Microsoft.Extensions.Diagnostics.Abstractions.Default;
                yield return Microsoft.Extensions.Diagnostics.HealthChecks.Default;
                yield return Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.Default;
                yield return Microsoft.Extensions.Features.Default;
                yield return Microsoft.Extensions.FileProviders.Abstractions.Default;
                yield return Microsoft.Extensions.FileProviders.Composite.Default;
                yield return Microsoft.Extensions.FileProviders.Embedded.Default;
                yield return Microsoft.Extensions.FileProviders.Physical.Default;
                yield return Microsoft.Extensions.FileSystemGlobbing.Default;
                yield return Microsoft.Extensions.Hosting.Default;
                yield return Microsoft.Extensions.Hosting.Abstractions.Default;
                yield return Microsoft.Extensions.Http.Default;
                yield return Microsoft.Extensions.Identity.Core.Default;
                yield return Microsoft.Extensions.Identity.Stores.Default;
                yield return Microsoft.Extensions.Localization.Default;
                yield return Microsoft.Extensions.Localization.Abstractions.Default;
                yield return Microsoft.Extensions.Logging.Default;
                yield return Microsoft.Extensions.Logging.Abstractions.Default;
                yield return Microsoft.Extensions.Logging.Configuration.Default;
                yield return Microsoft.Extensions.Logging.Console.Default;
                yield return Microsoft.Extensions.Logging.Debug.Default;
                yield return Microsoft.Extensions.Logging.EventLog.Default;
                yield return Microsoft.Extensions.Logging.EventSource.Default;
                yield return Microsoft.Extensions.Logging.TraceSource.Default;
                yield return Microsoft.Extensions.ObjectPool.Default;
                yield return Microsoft.Extensions.Options.Default;
                yield return Microsoft.Extensions.Options.ConfigurationExtensions.Default;
                yield return Microsoft.Extensions.Options.DataAnnotations.Default;
                yield return Microsoft.Extensions.Primitives.Default;
                yield return Microsoft.Extensions.WebEncoders.Default;
                yield return Microsoft.JSInterop.Default;
                yield return Microsoft.Net.Http.Headers.Default;
                yield return Microsoft.VisualBasic.Default;
                yield return Microsoft.VisualBasic.Core.Default;
                yield return Microsoft.VisualBasic.Forms.Default;
                yield return Microsoft.Win32.Primitives.Default;
                yield return Microsoft.Win32.Registry.Default;
                yield return Microsoft.Win32.Registry.AccessControl.Default;
                yield return Microsoft.Win32.SystemEvents.Default;
                yield return mscorlib.Default;
                yield return netstandard.Default;
                yield return PresentationCore.Default;
                yield return PresentationFramework.Default;
                yield return PresentationFramework.Aero.Default;
                yield return PresentationFramework.Aero2.Default;
                yield return PresentationFramework.AeroLite.Default;
                yield return PresentationFramework.Classic.Default;
                yield return PresentationFramework.Luna.Default;
                yield return PresentationFramework.Royale.Default;
                yield return PresentationFramework_SystemCore.Default;
                yield return PresentationFramework_SystemData.Default;
                yield return PresentationFramework_SystemDrawing.Default;
                yield return PresentationFramework_SystemXml.Default;
                yield return PresentationFramework_SystemXmlLinq.Default;
                yield return PresentationUI.Default;
                yield return ReachFramework.Default;
                yield return System.Default;
                yield return System.AppContext.Default;
                yield return System.Buffers.Default;
                yield return System.CodeDom.Default;
                yield return System.Collections.Default;
                yield return System.Collections.Concurrent.Default;
                yield return System.Collections.Immutable.Default;
                yield return System.Collections.NonGeneric.Default;
                yield return System.Collections.Specialized.Default;
                yield return System.ComponentModel.Default;
                yield return System.ComponentModel.Annotations.Default;
                yield return System.ComponentModel.DataAnnotations.Default;
                yield return System.ComponentModel.EventBasedAsync.Default;
                yield return System.ComponentModel.Primitives.Default;
                yield return System.ComponentModel.TypeConverter.Default;
                yield return System.Configuration.Default;
                yield return System.Configuration.ConfigurationManager.Default;
                yield return System.Console.Default;
                yield return System.Core.Default;
                yield return System.Data.Default;
                yield return System.Data.Common.Default;
                yield return System.Data.DataSetExtensions.Default;
                yield return System.Design.Default;
                yield return System.Diagnostics.Contracts.Default;
                yield return System.Diagnostics.Debug.Default;
                yield return System.Diagnostics.DiagnosticSource.Default;
                yield return System.Diagnostics.EventLog.Default;
                yield return System.Diagnostics.EventLog.Messages.Default;
                yield return System.Diagnostics.FileVersionInfo.Default;
                yield return System.Diagnostics.PerformanceCounter.Default;
                yield return System.Diagnostics.Process.Default;
                yield return System.Diagnostics.StackTrace.Default;
                yield return System.Diagnostics.TextWriterTraceListener.Default;
                yield return System.Diagnostics.Tools.Default;
                yield return System.Diagnostics.TraceSource.Default;
                yield return System.Diagnostics.Tracing.Default;
                yield return System.DirectoryServices.Default;
                yield return System.Drawing.Default;
                yield return System.Drawing.Common.Default;
                yield return System.Drawing.Design.Default;
                yield return System.Drawing.Primitives.Default;
                yield return System.Dynamic.Runtime.Default;
                yield return System.Formats.Asn1.Default;
                yield return System.Formats.Tar.Default;
                yield return System.Globalization.Default;
                yield return System.Globalization.Calendars.Default;
                yield return System.Globalization.Extensions.Default;
                yield return System.IO.Default;
                yield return System.IO.Compression.Default;
                yield return System.IO.Compression.Brotli.Default;
                yield return System.IO.Compression.FileSystem.Default;
                yield return System.IO.Compression.ZipFile.Default;
                yield return System.IO.FileSystem.Default;
                yield return System.IO.FileSystem.AccessControl.Default;
                yield return System.IO.FileSystem.DriveInfo.Default;
                yield return System.IO.FileSystem.Primitives.Default;
                yield return System.IO.FileSystem.Watcher.Default;
                yield return System.IO.IsolatedStorage.Default;
                yield return System.IO.MemoryMappedFiles.Default;
                yield return System.IO.Packaging.Default;
                yield return System.IO.Pipelines.Default;
                yield return System.IO.Pipes.Default;
                yield return System.IO.Pipes.AccessControl.Default;
                yield return System.IO.UnmanagedMemoryStream.Default;
                yield return System.Linq.Default;
                yield return System.Linq.Expressions.Default;
                yield return System.Linq.Parallel.Default;
                yield return System.Linq.Queryable.Default;
                yield return System.Memory.Default;
                yield return System.Net.Default;
                yield return System.Net.Http.Default;
                yield return System.Net.Http.Json.Default;
                yield return System.Net.HttpListener.Default;
                yield return System.Net.Mail.Default;
                yield return System.Net.NameResolution.Default;
                yield return System.Net.NetworkInformation.Default;
                yield return System.Net.Ping.Default;
                yield return System.Net.Primitives.Default;
                yield return System.Net.Quic.Default;
                yield return System.Net.Requests.Default;
                yield return System.Net.Security.Default;
                yield return System.Net.ServicePoint.Default;
                yield return System.Net.Sockets.Default;
                yield return System.Net.WebClient.Default;
                yield return System.Net.WebHeaderCollection.Default;
                yield return System.Net.WebProxy.Default;
                yield return System.Net.WebSockets.Default;
                yield return System.Net.WebSockets.Client.Default;
                yield return System.Numerics.Default;
                yield return System.Numerics.Vectors.Default;
                yield return System.ObjectModel.Default;
                yield return System.Printing.Default;
                yield return System.Private.CoreLib.Default;
                yield return System.Private.DataContractSerialization.Default;
                yield return System.Private.Uri.Default;
                yield return System.Private.Xml.Default;
                yield return System.Private.Xml.Linq.Default;
                yield return System.Reflection.Default;
                yield return System.Reflection.DispatchProxy.Default;
                yield return System.Reflection.Emit.Default;
                yield return System.Reflection.Emit.ILGeneration.Default;
                yield return System.Reflection.Emit.Lightweight.Default;
                yield return System.Reflection.Extensions.Default;
                yield return System.Reflection.Metadata.Default;
                yield return System.Reflection.Primitives.Default;
                yield return System.Reflection.TypeExtensions.Default;
                yield return System.Resources.Extensions.Default;
                yield return System.Resources.Reader.Default;
                yield return System.Resources.ResourceManager.Default;
                yield return System.Resources.Writer.Default;
                yield return System.Runtime.Default;
                yield return System.Runtime.CompilerServices.Unsafe.Default;
                yield return System.Runtime.CompilerServices.VisualC.Default;
                yield return System.Runtime.Extensions.Default;
                yield return System.Runtime.Handles.Default;
                yield return System.Runtime.InteropServices.Default;
                yield return System.Runtime.InteropServices.JavaScript.Default;
                yield return System.Runtime.InteropServices.RuntimeInformation.Default;
                yield return System.Runtime.InteropServices.WindowsRuntime.Default;
                yield return System.Runtime.Intrinsics.Default;
                yield return System.Runtime.Loader.Default;
                yield return System.Runtime.Numerics.Default;
                yield return System.Runtime.Serialization.Default;
                yield return System.Runtime.Serialization.Formatters.Default;
                yield return System.Runtime.Serialization.Json.Default;
                yield return System.Runtime.Serialization.Primitives.Default;
                yield return System.Runtime.Serialization.Xml.Default;
                yield return System.Runtime.WindowsRuntime.Default;
                yield return System.Runtime.WindowsRuntime.UI.Xaml.Default;
                yield return System.Security.Default;
                yield return System.Security.AccessControl.Default;
                yield return System.Security.Claims.Default;
                yield return System.Security.Cryptography.Default;
                yield return System.Security.Cryptography.Algorithms.Default;
                yield return System.Security.Cryptography.Cng.Default;
                yield return System.Security.Cryptography.Csp.Default;
                yield return System.Security.Cryptography.Encoding.Default;
                yield return System.Security.Cryptography.OpenSsl.Default;
                yield return System.Security.Cryptography.Pkcs.Default;
                yield return System.Security.Cryptography.Primitives.Default;
                yield return System.Security.Cryptography.ProtectedData.Default;
                yield return System.Security.Cryptography.X509Certificates.Default;
                yield return System.Security.Cryptography.Xml.Default;
                yield return System.Security.Permissions.Default;
                yield return System.Security.Principal.Default;
                yield return System.Security.Principal.Windows.Default;
                yield return System.Security.SecureString.Default;
                yield return System.ServiceModel.Web.Default;
                yield return System.ServiceProcess.Default;
                yield return System.Text.Encoding.Default;
                yield return System.Text.Encoding.CodePages.Default;
                yield return System.Text.Encoding.Extensions.Default;
                yield return System.Text.Encodings.Web.Default;
                yield return System.Text.Json.Default;
                yield return System.Text.RegularExpressions.Default;
                yield return System.Threading.Default;
                yield return System.Threading.AccessControl.Default;
                yield return System.Threading.Channels.Default;
                yield return System.Threading.Overlapped.Default;
                yield return System.Threading.RateLimiting.Default;
                yield return System.Threading.Tasks.Default;
                yield return System.Threading.Tasks.Dataflow.Default;
                yield return System.Threading.Tasks.Extensions.Default;
                yield return System.Threading.Tasks.Parallel.Default;
                yield return System.Threading.Thread.Default;
                yield return System.Threading.ThreadPool.Default;
                yield return System.Threading.Timer.Default;
                yield return System.Transactions.Default;
                yield return System.Transactions.Local.Default;
                yield return System.ValueTuple.Default;
                yield return System.Web.Default;
                yield return System.Web.HttpUtility.Default;
                yield return System.Windows.Default;
                yield return System.Windows.Controls.Ribbon.Default;
                yield return System.Windows.Extensions.Default;
                yield return System.Windows.Forms.Default;
                yield return System.Windows.Forms.Design.Default;
                yield return System.Windows.Forms.Design.Editors.Default;
                yield return System.Windows.Forms.Primitives.Default;
                yield return System.Windows.Input.Manipulations.Default;
                yield return System.Windows.Presentation.Default;
                yield return System.Xaml.Default;
                yield return System.Xml.Default;
                yield return System.Xml.Linq.Default;
                yield return System.Xml.ReaderWriter.Default;
                yield return System.Xml.Serialization.Default;
                yield return System.Xml.XDocument.Default;
                yield return System.Xml.XmlDocument.Default;
                yield return System.Xml.XmlSerializer.Default;
                yield return System.Xml.XPath.Default;
                yield return System.Xml.XPath.XDocument.Default;
                yield return UIAutomationClient.Default;
                yield return UIAutomationClientSideProviders.Default;
                yield return UIAutomationProvider.Default;
                yield return UIAutomationTypes.Default;
                yield return WindowsBase.Default;
                yield return WindowsFormsIntegration.Default;
            }

        }

        public static string NETCore = "Microsoft.NETCore.App";
        public static string WindowsDesktop = "Microsoft.WindowsDesktop.App";
        public static string AspNetCore = "Microsoft.AspNetCore.App";

        public static Version Version31 = new Version("3.1");
        public static Version Version50 = new Version("5.0");
        public static Version Version60 = new Version("6.0");
        public static Version Version70 = new Version("7.0");
        public static Version Version80 = new Version("8.0");

    }


}
