<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Bb</RootNamespace>
    <Description>Helper for compile Csharp at runtime</Description>
    <RepositoryUrl>https://github.com/Black-Beard-Sdk/Black.Beard.Roslyn</RepositoryUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageProjectUrl></PackageProjectUrl>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Generators\SourceCodeDomGenerator.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Black.Beard.Expressions" Version="1.0.196" />
		<PackageReference Include="System.CodeDom" Version="9.0.4" />
		<PackageReference Include="Vsxmd" Version="1.4.5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Generators\Csharp\LocalCSharpCodeProvider.cs" />
		<Compile Update="Generators\Csharp\ResourceString.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ResourceString.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Generators\Csharp\ResourceString.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>ResourceString.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

  <PropertyGroup>
    <DocumentationMarkdown>$(MSBuildProjectDirectory)\..\..\Docs\$(MSBuildProjectName).md</DocumentationMarkdown>
  </PropertyGroup>

  <PropertyGroup>
    <VsxmdAutoDeleteXml>True</VsxmdAutoDeleteXml>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  
</Project>
